const showAll = $("#all-filter")
const showDev = $("#dev-filter")
const showDesign = $("#design-filter")

showDev.click(function(){
    $(".design").hide()
    $(".dev").show()
    showDev.css("background-color", "black")
    showDev.css("color", "white")
    showDesign.css("background-color", "white")
    showDesign.css("color", "black")
    showAll.css("background-color", "white")
    showAll.css("color", "black")
})
showDesign.click(function(){
    $(".dev").hide()
    $(".design").show()
    showDesign.css("background-color", "black")
    showDesign.css("color", "white")
    showDev.css("background-color", "white")
    showDev.css("color", "black")
    showAll.css("background-color", "white")
    showAll.css("color", "black")
})

showAll.click(function(){
    $(".dev").show()
    $(".design").show()
    showDesign.css("background-color", "white")
    showDesign.css("color", "black")
    showDev.css("background-color", "white")
    showDev.css("color", "black")
    showAll.css("background-color", "black")
    showAll.css("color", "white")
})